### ISSUE TITLE
BUG: need to handle "&" differently

### ISSUE THREAD

**Issue by planetrenox** [cicirello/generate-sitemap#123]
**Describe the bug**
If there is an `&` in the URL, according to chatgpt it needs to be parsed to `&amp;`

**To Reproduce**
For example the url
`<loc>https://planetrenox.pages.dev/gv/terms&policies</loc>`
is wrong

**Expected behavior**
`<loc>https://planetrenox.pages.dev/gv/terms&amp;policies</loc>`

**Additional context**
I might be wrong about the fix but on github, it flags the file as red so it seems like it's def wrong with the current.

**Comment by cicirello** [comment]
@planetrenox thanks for reporting. It hadn't occurred to me that someone might have `&` in a filename. `&` is an illegal character in XML files since it starts escape sequences, and must be escaped with `&amp;`. This should be easy enough to fix though. There are a couple other such characters that are also not being handled.

**Comment by cicirello** [comment]
@planetrenox this is now fixed in `v1.10.1` and the patch is also available via the major version tag `v1` 🚀
